// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScreenTemperature;

#nullable disable

namespace ScreenTemperature.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("ScreenTemperature.Entities.Configurations.Configuration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Brightness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DevicePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ScreenTemperature.Entities.KeyBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Alt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Control")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Shift")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("KeyBindings");
                });

            modelBuilder.Entity("ScreenTemperature.Entities.KeyBindingActions.KeyBindingAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KeyBindingId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeyBindingId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ScreenTemperature.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("ScreenTemperature.Entities.Configurations.ColorConfiguration", b =>
                {
                    b.HasBaseType("ScreenTemperature.Entities.Configurations.Configuration");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("ColorConfigurations");
                });

            modelBuilder.Entity("ScreenTemperature.Entities.Configurations.TemperatureConfiguration", b =>
                {
                    b.HasBaseType("ScreenTemperature.Entities.Configurations.Configuration");

                    b.Property<int>("Intensity")
                        .HasColumnType("INTEGER");

                    b.ToTable("TemperatureConfigurations");
                });

            modelBuilder.Entity("ScreenTemperature.Entities.KeyBindingActions.ApplyConfiguration", b =>
                {
                    b.HasBaseType("ScreenTemperature.Entities.KeyBindingActions.KeyBindingAction");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("TEXT");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("ApplyConfigurationActions");
                });

            modelBuilder.Entity("ScreenTemperature.Entities.KeyBindingActions.DecreaseBrightnessBy", b =>
                {
                    b.HasBaseType("ScreenTemperature.Entities.KeyBindingActions.KeyBindingAction");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.ToTable("DecreaseBrightnessByActions");
                });

            modelBuilder.Entity("ScreenTemperature.Entities.KeyBindingActions.IncreaseBrightnessBy", b =>
                {
                    b.HasBaseType("ScreenTemperature.Entities.KeyBindingActions.KeyBindingAction");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.ToTable("IncreaseBrightnessByActions");
                });

            modelBuilder.Entity("ScreenTemperature.Entities.KeyBindingActions.SetBrightnessTo", b =>
                {
                    b.HasBaseType("ScreenTemperature.Entities.KeyBindingActions.KeyBindingAction");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.ToTable("SetBrightnessToActions");
                });

            modelBuilder.Entity("ScreenTemperature.Entities.Configurations.Configuration", b =>
                {
                    b.HasOne("ScreenTemperature.Entities.Profile", "Profile")
                        .WithMany("Configurations")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ScreenTemperature.Entities.KeyBindingActions.KeyBindingAction", b =>
                {
                    b.HasOne("ScreenTemperature.Entities.KeyBinding", "KeyBinding")
                        .WithMany("Actions")
                        .HasForeignKey("KeyBindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KeyBinding");
                });

            modelBuilder.Entity("ScreenTemperature.Entities.KeyBindingActions.ApplyConfiguration", b =>
                {
                    b.HasOne("ScreenTemperature.Entities.Profile", "Configuration")
                        .WithMany()
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("ScreenTemperature.Entities.KeyBinding", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("ScreenTemperature.Entities.Profile", b =>
                {
                    b.Navigation("Configurations");
                });
#pragma warning restore 612, 618
        }
    }
}
